version: "3.8"

x-args: &args
  PROJECT_NAME: ${PROJECT_NAME:-web-tura}
  NEXT_PUBLIC_CHAIN_TYPE: ${NEXT_PUBLIC_CHAIN_TYPE:-}
  TURBO_TEAM: ${TURBO_TEAM:-}                         # for Turborepo remote cache
  TURBO_TOKEN: ${TURBO_TOKEN:-}                       # for Turborepo remote cache
  NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN:-} # for Sentry.io
  SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN:-}           # for Sentry.io

x-build: &build
  context: .
  args: *args
  target: runner

x-web: &web-tura
  build: *build
  restart: always
  ports:
    - ${PORT:-5000}:${PORT:-5000}
  networks:
    - app_network
  env_file: .env

services:
  # default web
  web: *web-tura
  # for mac with M1/M2 chip
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    driver: bridge
